### ISSUE TITLE
tcp connection not established

### ISSUE THREAD

**Issue by TcM1911** [bitchan/bitmessage-transports#3]
When I'm running the networking example code below it does not establishing a connection.

```
var messages = require("bitmessage").messages;
var TcpTransport = require("bitmessage-transports").TcpTransport;

var tcp = new TcpTransport({
  dnsSeeds: [["bootstrap8444.bitmessage.org", 8444]],
});

tcp.bootstrap().then(function(nodes) {
  var remoteHost = nodes[0][0];
  var remotePort = nodes[0][1];
  console.log("Connecting to", nodes[0]);
  tcp.connect(remotePort, remoteHost);
});

tcp.on("established", function(version) {
  console.log("Connection established to", version.userAgent);

  tcp.on("message", function(command, payload) {
    console.log("Got new", command, "message");
    var decoded;
    if (command === "addr") {
      decoded = messages.addr.decodePayload(payload);
      console.log("Got", decoded.addrs.length, "node addresses");
    }
  });
});
```

An initial syn package is sent followed by 6 re-transmissions and than it just sits until it crashes with the output below.

```
node test_code.js 
Connecting to [ '118.169.41.196', 8444 ]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

Everything is fine if I'm running the tests for the library, no problem with establishing a tcp connection with localhost. Do you have any idea of why it's not working?

Many thanks.

**Comment by Kagami** [comment]
Sorry for the delay.

Well, the problem is bootstrap seeds return too many dead nodes. There was [bitmessage.mobi](http://bitmessage.mobi/bitmessaged/nodes) service which contained alive seeds but now it's unavailable. I suggest you to look at PyBitmessage log and try to connect to recent nodes. Note: PyBitmessage accepts only one connection per IP so you need to either shutdown your PyBitmessage client if it's running and connected to that node or look for some elder node.

I was able to successfully connect to `8.8.248.7:8444` by passing `seeds: [["8.8.248.7", 8444]]` option to `TcpTransport` instead of `dnsSeeds` but it might be dead when you'll try to connect.

**Comment by TcM1911** [comment]
Hi,

Thanks for your reply. It makes more sense to me now. This can be a nasty bug. Do you think it's possible to do a bootstrap connection to a good node. Maybe have a timeout limit in the connection process. If it can't establish a connection within a time frame, drop the connection and try another node from the list generated during the bootstrap. 

What's your thought?

**Comment by Kagami** [comment]
> Maybe have a timeout limit in the connection process. If it can't establish a connection within a time frame, drop the connection and try another node from the list generated during the bootstrap.

Correct, this is how you should manage connection logic inside your application. But it's high-level logic and `bitmessage-transports` provides only tiny primitives which allows you to implement this logic by yourself. If you want example of high-level application on top of `bitmessage`/`bitmessage-transports`, take a look at [bitchan-node](https://github.com/bitchan/bitchan-node/blob/master/src/net/tcp.js).

Have you managed to connect to non-localhost node with `bitmessage-transports`?

**Comment by TcM1911** [comment]
Thanks. You're right. Thanks for the implementation example. Connecting to active nodes works.
